name: skeletix
description: "A highly advanced, strictly declarative RenderObject automated skeleton generator. Intelligently scans layouts to automatically draw precision placeholders without rigid boilerplate."
version: 1.0.1
homepage: "https://github.com/developermanishdevan/skeletix"
repository: "https://github.com/developermanishdevan/skeletix"
issue_tracker: "https://github.com/developermanishdevan/skeletix/issues"
topics:
  - skeleton
  - loading
  - shimmer
  - ui
  - animation

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
